# Generated by Django 5.0.3 on 2024-03-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hash_tag',
            field=models.CharField(max_length=20, null=True, verbose_name='해시태그'),
        ),
    ]
